### ISSUE TITLE
push issue with navigator

### ISSUE THREAD

**Issue by rucko24** [m1kah/vaadin-grid-push#1]
Hi,
thank you for this example really works, but I do not understand when I include your example with the Navigator view the push stops? just clicking on the buttons to change views stops working the push

**Comment by m1kah** [comment]
Nice. Please have a look at feature/navigator branch. I created a navigator there with 2 different views.

https://github.com/m1kah/vaadin-grid-push/tree/feature/navigator

Does this solve your problem?

**Comment by rucko24** [comment]
thanks so much @m1kah , it works...
